#!/usr/bin/python3

import sys
import psutil
import platform
from datetime import datetime

if (len(sys.argv) > 1):
    if (sys.argv[1] == "cpu" ):
        print (f"system.cpu.idle {psutil.cpu_times()[3]}")
        print (f"system.cpu.user {psutil.cpu_times()[0]}")
        print (f"system.cpu.iowait {psutil.cpu_times()[4]}")
        print (f"system.cpu.stolen {psutil.cpu_times()[7]}")
        print (f"system.cpu.system {psutil.cpu_times()[2]}")

    elif (sys.argv[1] == "mem" ):
        print (f"virtual total {psutil.virtual_memory()[0]}")
        print (f"virtual used {psutil.virtual_memory()[3]}")
        print (f"virtual free {psutil.virtual_memory()[4]}")
        print (f"virtual shared {psutil.virtual_memory()[9]}")
        print (f"swap total {psutil.swap_memory()[0]}")
        print (f"swap used {psutil.swap_memory()[1]}")
        print (f"swap free {psutil.swap_memory()[2]}")

else:
    print ("No arguments or wrong arguments")
